<?php
session_start();
require_once 'functions.php';
if (!isset($_SESSION['loggedin'])) {
    header('Location: login.php');
        exit;
        }

        $uploadDir = 'uploads/';
        $files = array_diff(scandir($uploadDir), array('.', '..'));

        if (isset($_GET['delete'])) {
            $fileToDelete = $uploadDir . basename($_GET['delete']);
                if (file_exists($fileToDelete)) {
                        unlink($fileToDelete);
                                header("Location: admin.php");
                                    }
                                    }
                                    ?>
                                    <!DOCTYPE html>
                                    <html lang="pt-BR">
                                    <head>
                                        <meta charset="UTF-8">
                                            <meta name="viewport" content="width=device-width, initial-scale=1">
                                                <title>Painel Administrativo - myup</title>
                                                    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
                                                        <style>
                                                                .card-img-top, video {
                                                                            max-height: 200px;
                                                                                        object-fit: cover;
                                                                                                }
                                                                                                        .card {
                                                                                                                    height: 100%;
                                                                                                                            }
                                                                                                                                </style>
                                                                                                                                </head>
                                                                                                                                <body class="bg-light">

                                                                                                                                <div class="container mt-4">
                                                                                                                                    <div class="d-flex justify-content-between align-items-center mb-4">
                                                                                                                                            <h2>Painel Administrativo</h2>
                                                                                                                                                    <a href="logout.php" class="btn btn-danger">Sair</a>
                                                                                                                                                        </div>

                                                                                                                                                            <div class="row g-4">
                                                                                                                                                                <?php if (!empty($files)): ?>
                                                                                                                                                                        <?php foreach ($files as $file): ?>
                                                                                                                                                                                    <?php
                                                                                                                                                                                                    $filePath = $uploadDir . $file;
                                                                                                                                                                                                                    $fileUrl = 'uploads/' . urlencode($file);
                                                                                                                                                                                                                                    $fileDate = date("d/m/Y H:i", filemtime($filePath));
                                                                                                                                                                                                                                                    $type = isImage($file) ? "Imagem" : (isVideo($file) ? "Vídeo" : "Outro");
                                                                                                                                                                                                                                                                ?>
                                                                                                                                                                                                                                                                            <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                                                                                                                                                                                                                                                                                            <div class="card shadow-sm h-100">
                                                                                                                                                                                                                                                                                                                <?php if (isImage($file)): ?>
                                                                                                                                                                                                                                                                                                                                        <img src="<?php echo $fileUrl; ?>" class="card-img-top">
                                                                                                                                                                                                                                                                                                                                                            <?php elseif (isVideo($file)): ?>
                                                                                                                                                                                                                                                                                                                                                                                    <video controls class="w-100">
                                                                                                                                                                                                                                                                                                                                                                                                                <source src="<?php echo $fileUrl; ?>" type="video/mp4">
                                                                                                                                                                                                                                                                                                                                                                                                                                            Seu navegador não suporta vídeos.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </video>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div class="card-body text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h6 class="card-title small"><?php echo htmlspecialchars($file); ?></h6>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p class="text-muted small"><?php echo $type; ?> • <?php echo $fileDate; ?></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <a class="btn btn-sm btn-primary w-100 mb-2" href="<?php echo $fileUrl; ?>" target="_blank">Visualizar</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <a class="btn btn-sm btn-outline-danger w-100" href="?delete=<?php echo urlencode($file); ?>" onclick="return confirm('Excluir este arquivo?')">Excluir</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php endforeach; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <?php else: ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p class="text-center">Nenhum arquivo enviado ainda.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </html>