<?php
require_once 'functions.php';

$uploadDir = 'uploads/';
$files = [];
if (is_dir($uploadDir)) {
    $files = array_diff(scandir($uploadDir), array('.', '..'));
    }
    ?>
    <!DOCTYPE html>
    <html lang="pt-BR">
    <head>
        <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1"> <!-- Responsivo -->
                <title>myup - Plataforma de Upload</title>
                    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
                        <style>
                                .card-img-top, video {
                                            max-height: 200px;
                                                        object-fit: cover;
                                                                }
                                                                        .card {
                                                                                    height: 100%;
                                                                                            }
                                                                                                    .card-body {
                                                                                                                display: flex;
                                                                                                                            flex-direction: column;
                                                                                                                                        justify-content: space-between;
                                                                                                                                                }
                                                                                                                                                    </style>
                                                                                                                                                    </head>
                                                                                                                                                    <body class="bg-light">

                                                                                                                                                    <div class="container mt-4">
                                                                                                                                                        <h1 class="text-center mb-4">Bem-vindo ao <strong>myup</strong>!</h1>

                                                                                                                                                            <div class="d-flex justify-content-center flex-wrap mb-5">
                                                                                                                                                                    <a href="upload.php" class="btn btn-success m-2">Enviar Novo Arquivo</a>
                                                                                                                                                                            <a href="login.php" class="btn btn-primary m-2">Área Administrativa</a>
                                                                                                                                                                                </div>

                                                                                                                                                                                    <h2 class="text-center mb-4">Arquivos Enviados</h2>
                                                                                                                                                                                        <div class="row g-4">
                                                                                                                                                                                            <?php if (!empty($files)): ?>
                                                                                                                                                                                                    <?php foreach ($files as $file): ?>
                                                                                                                                                                                                                <?php
                                                                                                                                                                                                                                $filePath = $uploadDir . $file;
                                                                                                                                                                                                                                                $fileUrl = 'uploads/' . urlencode($file);
                                                                                                                                                                                                                                                                $fileDate = date("d/m/Y H:i", filemtime($filePath));
                                                                                                                                                                                                                                                                                $type = isImage($file) ? "Imagem" : (isVideo($file) ? "Vídeo" : "Outro");
                                                                                                                                                                                                                                                                                            ?>
                                                                                                                                                                                                                                                                                                        <div class="col-12 col-sm-6 col-md-4 col-lg-3">
                                                                                                                                                                                                                                                                                                                        <div class="card shadow-sm h-100">
                                                                                                                                                                                                                                                                                                                                            <?php if (isImage($file)): ?>
                                                                                                                                                                                                                                                                                                                                                                    <img src="<?php echo $fileUrl; ?>" class="card-img-top">
                                                                                                                                                                                                                                                                                                                                                                                        <?php elseif (isVideo($file)): ?>
                                                                                                                                                                                                                                                                                                                                                                                                                <video controls class="w-100">
                                                                                                                                                                                                                                                                                                                                                                                                                                            <source src="<?php echo $fileUrl; ?>" type="video/mp4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Seu navegador não suporta vídeos.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </video>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div class="card-body text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h6 class="card-title small"><?php echo htmlspecialchars($file); ?></h6>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p class="text-muted small"><?php echo $type; ?> • <?php echo $fileDate; ?></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <a class="btn btn-sm btn-primary mb-2 w-100" href="<?php echo $fileUrl; ?>" target="_blank">Visualizar</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <a class="btn btn-sm btn-outline-secondary w-100" href="<?php echo $fileUrl; ?>" download>Baixar</a>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php endforeach; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <?php else: ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p class="text-center">Nenhum arquivo enviado ainda.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <?php endif; ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </html>